sudo: false

language: python

services:
  - mongodb

python:
  - "2.7.11" 

# command to install dependencies
install: 
  - pip install -r requirements.txt

# command to run tests
script:
  - python main.py --travis True
  - cat log.txt
